### ISSUE TITLE
CLI with text output

### ISSUE THREAD

**Issue by CobusT** [asg017/observable-prerender#11]
I love this. 
Could you add txt as an output type for the CLI? Or even console?
That would allow me to use a function in Observable with a notebook like this:
https://observablehq.com/@cobus/prerender-test

**Comment by asg017** [comment]
Yo thanks for the feature request! This seems totally reasonable. It seems like adding a new `--stdout` flag and `--format text` option would be best, like this:

``` bash
# Write output to sample.txt
$ observable-prerender @cobus/pretender-test output \
   --redefine inputData:bbb 
   --format text --out sample.txt

# Write output to stdout
$ observable-prerender @cobus/pretender-test output \
   --redefine inputData:bbb 
   --format text --stdout
```

I've got a couple changes/features coming in soon along with this, so may take some time until I get this feature in. As a workaround, you can create a script that uses the node API to do what you want (which you have in that notebook).

**Comment by CobusT** [comment]
That would be awesome! 
Thanks

**Comment by asg017** [comment]
Update: `v0.3.0` Now has this functionality. If you pass in `"-"` as the output file name, it will print the data to `stdout`. `--format txt` or `--format text` is an option as well.

For your example:

```
$ observable-prerender @cobus/prerender-test output --redefine inputData:yoo --format txt --out -
You passed in yoo
```

To update your `observable-prerender` version:

```
npm i -g @alex.garcia/observable-prerender@v0.3.0
```

Let me know if it works! Planning to add some `--format json` and other misc options soon as well.

**Comment by CobusT** [comment]
Awesome. It works!!!
