### ISSUE TITLE
error: width already defined

### ISSUE THREAD

**Issue by enjalot** [asg017/observable-prerender#6]
https://github.com/asg017/observable-prerender/blob/f804ae5335d9c1877face728244b1de94bc2d43f/bin/observable-prerender-animate#L85

running animate on my machine I ran into a problem with this line. I deleted it and things were happy.
I'm running node v12.16.1 idk if that matters

**Comment by asg017** [comment]
Hey thanks for raising this and for pointing out a quick fix! I should really set up some tests for these CLI's, guess I was too publish-happy...

`v0.1.2` has the fix, you can update with:

```
npm update @alex.garcia/observable-prerender
```

And `observable-prerender --version` or `observable-prerender-animate --version` to verify your CLI is on the right version.
